#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration: Release

build:
  project: NuCake.sln

before_build:
  - nuget restore

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: output\*.nupkg

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

#deploy:
#  provider: NuGet
#  api_key:
#    secure: zcdil8N+M2gC4/yejAz7hekwC3rt7qg2YTg596STxTrv/EJeTlqtb3MT6H5Cao6W